version: '3.7'
services:
  api:
    image: "judge-api"
    ports:
      - "8080:8080"
    restart: 'unless-stopped'
    env_file: ../.docker.env
    networks:
      - system
    depends_on:
      db:
        condition: service_started
  isolate:
    image: "judge-isolate"
    privileged: true
    restart: 'unless-stopped'
    networks:
      - system
    depends_on:
      db:
        condition: service_started
  db:
    image: mysql:8
    ports:
      - '3306:3306'
    restart: 'unless-stopped'
    environment:
      - MYSQL_ROOT_PASSWORD=hoplin1234!
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=judge
    networks:
      - system
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - system
  rmq:
    image: rabbitmq:3-management
    ports:
      - '1883:1883'
      - '15672:15672'
      - '5672:5672'
    restart: 'unless-stopped'
    networks:
      - system
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=password
networks:
  system:
    driver: bridge
